/* Generated By:JavaCC: Do not edit this line. AssignmentConstants.java */

/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface AssignmentConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int DIGIT = 1;
  /** RegularExpression Id. */
  int PLUS = 2;
  /** RegularExpression Id. */
  int MULTIPLY = 3;
  /** RegularExpression Id. */
  int DEFINITION = 4;
  /** RegularExpression Id. */
  int PARAMATER = 5;
  /** RegularExpression Id. */
  int LINEEND = 6;
  /** RegularExpression Id. */
  int FUNC = 7;
  /** RegularExpression Id. */
  int MAIN = 8;
  /** RegularExpression Id. */
  int SEMICOLON = 9;
  /** RegularExpression Id. */
  int SPACE = 10;
  /** RegularExpression Id. */
  int OPENBRAC = 11;
  /** RegularExpression Id. */
  int CLOSEBRAC = 12;
  /** RegularExpression Id. */
  int OPENCURLYBRAC = 13;
  /** RegularExpression Id. */
  int CLOSECURLYBRAC = 14;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "<DIGIT>",
    "\"+\"",
    "\"*\"",
    "\"DEF\"",
    "<PARAMATER>",
    "\"\\n\"",
    "<FUNC>",
    "\"MAIN\"",
    "\";\"",
    "\" \"",
    "\"(\"",
    "\")\"",
    "\"{\"",
    "\"}\"",
  };

}
